// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleScssNamespace {
    export interface IStyleScss {
        bullet: string;
        center: string;
        error: string;
        footer: string;
        green: string;
        hide: string;
        label: string;
        links: string;
        loading: string;
        ok: string;
        panel: string;
        red: string;
        results: string;
        spark: string;
    }
}

declare const StyleScssModule: StyleScssNamespace.IStyleScss;

export = StyleScssModule;
